<?php

namespace ContainerW1D6HDh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XdoDj7NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xdoDj7N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sampana' => ['privates', '.errored..service_locator.xdoDj7N.App\\Entity\\Sampana', NULL, 'Cannot autowire service ".service_locator.xdoDj7N": it needs an instance of "App\\Entity\\Sampana" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'sampana' => 'App\\Entity\\Sampana',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.xdoDj7N'])) {
            return $container->privates['.service_locator.xdoDj7N'];
        }

        return $container->privates['.service_locator.xdoDj7N'] = $instance;
    }
}
