<?php

namespace Container1vpJmXw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JTMdNTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JT_mdNT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ActualiteController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\ActualiteController::index()', 'getActualiteControllerindexService', true],
            'App\\Controller\\ActualiteController::show' => ['privates', '.service_locator.9BiSpWR.App\\Controller\\ActualiteController::show()', 'getActualiteControllershowService', true],
            'App\\Controller\\ActualiteController::category' => ['privates', '.service_locator.3yATBZT.App\\Controller\\ActualiteController::category()', 'getActualiteControllercategoryService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ActualiteController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\ActualiteController::index()', 'getActualiteControllerindexService', true],
            'App\\Controller\\ActualiteController:show' => ['privates', '.service_locator.9BiSpWR.App\\Controller\\ActualiteController::show()', 'getActualiteControllershowService', true],
            'App\\Controller\\ActualiteController:category' => ['privates', '.service_locator.3yATBZT.App\\Controller\\ActualiteController::category()', 'getActualiteControllercategoryService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ActualiteController::index' => '?',
            'App\\Controller\\ActualiteController::show' => '?',
            'App\\Controller\\ActualiteController::category' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ActualiteController:index' => '?',
            'App\\Controller\\ActualiteController:show' => '?',
            'App\\Controller\\ActualiteController:category' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.JT_mdNT'])) {
            return $container->privates['.service_locator.JT_mdNT'];
        }

        return $container->privates['.service_locator.JT_mdNT'] = $instance;
    }
}
