<?php

namespace Container1vpJmXw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._WkUlH_.App\Controller\BlogController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._WkUlH_.App\\Controller\\BlogController::index()'] = ($container->privates['.service_locator._WkUlH_'] ?? $container->load('get_ServiceLocator_WkUlHService'))->withContext('App\\Controller\\BlogController::index()', $container);
    }
}
