vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer   
        post_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        sampana_image:
            uri_prefix: /images/sampana
            upload_destination: '%kernel.project_dir%/public/images/sampana'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        fivondronana_image:
            uri_prefix: /images/fivondronana
            upload_destination: '%kernel.project_dir%/public/images/fivondronana'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        mpiandrakitra_image:
            uri_prefix: /images/mpiandrakitra
            upload_destination: '%kernel.project_dir%/public/images/mpiandrakitra'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
