<?php

namespace ContainerYvltIin;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I0bBjrHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i0bBjrH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i0bBjrH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ActualiteController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\ActualiteController::index()', 'getActualiteControllerindexService', true],
            'App\\Controller\\ActualiteController::show' => ['privates', '.service_locator.cFKXuFt.App\\Controller\\ActualiteController::show()', 'getActualiteControllershowService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ActualiteController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\ActualiteController::index()', 'getActualiteControllerindexService', true],
            'App\\Controller\\ActualiteController:show' => ['privates', '.service_locator.cFKXuFt.App\\Controller\\ActualiteController::show()', 'getActualiteControllershowService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ActualiteController::index' => '?',
            'App\\Controller\\ActualiteController::show' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ActualiteController:index' => '?',
            'App\\Controller\\ActualiteController:show' => '?',
            'App\\Controller\\BlogController:index' => '?',
        ]);
    }
}
