<?php

namespace ContainerP510nyj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFivondronannaControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uf7tg7R.App\Controller\admin\FivondronannaController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fivondronanna' => ['privates', '.errored..service_locator.uf7tg7R.App\\Entity\\Fivondronana', NULL, 'Cannot autowire service ".service_locator.uf7tg7R": it needs an instance of "App\\Entity\\Fivondronana" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'fivondronanna' => 'App\\Entity\\Fivondronana',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\admin\\FivondronannaController::edit()', $container);

        if (isset($container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'])) {
            return $container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'];
        }

        return $container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'] = $instance;
    }
}
