<?php

namespace ContainerP510nyj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostAdminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DiMdHbo.App\Controller\admin\PostAdminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\admin\\PostAdminController::index()', $container);

        if (isset($container->privates['.service_locator.DiMdHbo.App\\Controller\\admin\\PostAdminController::index()'])) {
            return $container->privates['.service_locator.DiMdHbo.App\\Controller\\admin\\PostAdminController::index()'];
        }

        return $container->privates['.service_locator.DiMdHbo.App\\Controller\\admin\\PostAdminController::index()'] = $instance;
    }
}
