<?php

namespace ContainerP510nyj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSampanaControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gx1d6qN.App\Controller\admin\SampanaController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sampanaRepository' => ['privates', 'App\\Repository\\SampanaRepository', 'getSampanaRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'sampanaRepository' => 'App\\Repository\\SampanaRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\admin\\SampanaController::index()', $container);

        if (isset($container->privates['.service_locator.gx1d6qN.App\\Controller\\admin\\SampanaController::index()'])) {
            return $container->privates['.service_locator.gx1d6qN.App\\Controller\\admin\\SampanaController::index()'];
        }

        return $container->privates['.service_locator.gx1d6qN.App\\Controller\\admin\\SampanaController::index()'] = $instance;
    }
}
