<?php

namespace ContainerUf8ddla;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFivondronannaControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2zIQrtK.App\Controller\admin\FivondronannaController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fivondronanaRepository' => ['privates', 'App\\Repository\\FivondronanaRepository', 'getFivondronanaRepositoryService', true],
        ], [
            'entityManager' => '?',
            'fivondronanaRepository' => 'App\\Repository\\FivondronanaRepository',
        ]))->withContext('App\\Controller\\admin\\FivondronannaController::new()', $container);

        if (isset($container->privates['.service_locator.2zIQrtK.App\\Controller\\admin\\FivondronannaController::new()'])) {
            return $container->privates['.service_locator.2zIQrtK.App\\Controller\\admin\\FivondronannaController::new()'];
        }

        return $container->privates['.service_locator.2zIQrtK.App\\Controller\\admin\\FivondronannaController::new()'] = $instance;
    }
}
