<?php

namespace ContainerUf8ddla;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFivondronannaControllerviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TvwUvss.App\Controller\admin\FivondronannaController::view()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TvwUvss.App\\Controller\\admin\\FivondronannaController::view()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fivondronanna' => ['privates', '.errored..service_locator.TvwUvss.App\\Entity\\Fivondronana', NULL, 'Cannot autowire service ".service_locator.TvwUvss": it needs an instance of "App\\Entity\\Fivondronana" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'fivondronanna' => 'App\\Entity\\Fivondronana',
        ]))->withContext('App\\Controller\\admin\\FivondronannaController::view()', $container);
    }
}
