<?php

namespace ContainerUf8ddla;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFivondronanaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TvwUvss.App\Entity\Fivondronana' shared service.
     *
     * @return \App\Entity\Fivondronana
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TvwUvss": it needs an instance of "App\\Entity\\Fivondronana" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
