<?php

namespace ContainerUf8ddla;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSampanaControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xdoDj7N.App\Controller\admin\SampanaController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xdoDj7N'] ?? $container->load('get_ServiceLocator_XdoDj7NService'));

        if (isset($container->privates['.service_locator.xdoDj7N.App\\Controller\\admin\\SampanaController::delete()'])) {
            return $container->privates['.service_locator.xdoDj7N.App\\Controller\\admin\\SampanaController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\admin\\SampanaController::delete()', $container);

        if (isset($container->privates['.service_locator.xdoDj7N.App\\Controller\\admin\\SampanaController::delete()'])) {
            return $container->privates['.service_locator.xdoDj7N.App\\Controller\\admin\\SampanaController::delete()'];
        }

        return $container->privates['.service_locator.xdoDj7N.App\\Controller\\admin\\SampanaController::delete()'] = $instance;
    }
}
