<?php

namespace ContainerQnZ2QXl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostAdminControllerapproveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EhRzrPc.App\Controller\admin\PostAdminController::approve()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.EhRzrPc.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.EhRzrPc": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'post' => 'App\\Entity\\Post',
            'em' => '?',
        ]))->withContext('App\\Controller\\admin\\PostAdminController::approve()', $container);

        if (isset($container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::approve()'])) {
            return $container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::approve()'];
        }

        return $container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::approve()'] = $instance;
    }
}
