<?php

namespace ContainerKEAplcy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostAdminControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3BoFVFw.App\Controller\admin\PostAdminController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\admin\\PostAdminController::new()', $container);

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\admin\\PostAdminController::new()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\admin\\PostAdminController::new()'];
        }

        return $container->privates['.service_locator.3BoFVFw.App\\Controller\\admin\\PostAdminController::new()'] = $instance;
    }
}
