<?php

namespace ContainerKEAplcy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingadminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4XYvBdG.App\Controller\admin\SettingadminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.4XYvBdG'] ?? $container->load('get_ServiceLocator_4XYvBdGService'));

        if (isset($container->privates['.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()'])) {
            return $container->privates['.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\admin\\SettingadminController::index()', $container);

        if (isset($container->privates['.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()'])) {
            return $container->privates['.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()'];
        }

        return $container->privates['.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()'] = $instance;
    }
}
