<?php

namespace ContainerD7nz6bH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_TransportFactory_MailgunService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.transport_factory.mailgun' shared service.
     *
     * @return \Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailgun-mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'MailgunTransportFactory.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['mailer.transport_factory.mailgun'])) {
            return $container->privates['mailer.transport_factory.mailgun'];
        }

        $instance = new \Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory($a, ($container->privates['http_client.uri_template'] ?? self::getHttpClient_UriTemplateService($container)), ($container->privates['monolog.logger.mailer'] ?? $container->load('getMonolog_Logger_MailerService')));

        if (isset($container->privates['mailer.transport_factory.mailgun'])) {
            return $container->privates['mailer.transport_factory.mailgun'];
        }

        return $container->privates['mailer.transport_factory.mailgun'] = $instance;
    }
}
