<?php

namespace ContainerN431NCO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uj7onLOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uj7onLO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ActualiteController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\ActualiteController::index()', 'getActualiteControllerindexService', true],
            'App\\Controller\\ActualiteController::show' => ['privates', '.service_locator.9BiSpWR.App\\Controller\\ActualiteController::show()', 'getActualiteControllershowService', true],
            'App\\Controller\\ActualiteController::category' => ['privates', '.service_locator.3yATBZT.App\\Controller\\ActualiteController::category()', 'getActualiteControllercategoryService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\admin\\PostAdminController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\admin\\PostAdminController::index()', 'getPostAdminControllerindexService', true],
            'App\\Controller\\admin\\PostAdminController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\admin\\PostAdminController::new()', 'getPostAdminControllernewService', true],
            'App\\Controller\\admin\\PostAdminController::approve' => ['privates', '.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::approve()', 'getPostAdminControllerapproveService', true],
            'App\\Controller\\admin\\PostAdminController::reject' => ['privates', '.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()', 'getPostAdminControllerrejectService', true],
            'App\\Controller\\admin\\SettingadminController::index' => ['privates', '.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()', 'getSettingadminControllerindexService', true],
            'App\\Controller\\admin\\SettingadminController::edit' => ['privates', '.service_locator.j3kKXma.App\\Controller\\admin\\SettingadminController::edit()', 'getSettingadminControllereditService', true],
            'App\\Controller\\admin\\SettingadminController::lists' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\admin\\SettingadminController::lists()', 'getSettingadminControllerlistsService', true],
            'App\\Controller\\admin\\UseradminController::index' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\admin\\UseradminController::index()', 'getUseradminControllerindexService', true],
            'App\\Controller\\admin\\UseradminController::new' => ['privates', '.service_locator.4XYvBdG.App\\Controller\\admin\\UseradminController::new()', 'getUseradminControllernewService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ActualiteController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\ActualiteController::index()', 'getActualiteControllerindexService', true],
            'App\\Controller\\ActualiteController:show' => ['privates', '.service_locator.9BiSpWR.App\\Controller\\ActualiteController::show()', 'getActualiteControllershowService', true],
            'App\\Controller\\ActualiteController:category' => ['privates', '.service_locator.3yATBZT.App\\Controller\\ActualiteController::category()', 'getActualiteControllercategoryService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\admin\\PostAdminController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\admin\\PostAdminController::index()', 'getPostAdminControllerindexService', true],
            'App\\Controller\\admin\\PostAdminController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\admin\\PostAdminController::new()', 'getPostAdminControllernewService', true],
            'App\\Controller\\admin\\PostAdminController:approve' => ['privates', '.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::approve()', 'getPostAdminControllerapproveService', true],
            'App\\Controller\\admin\\PostAdminController:reject' => ['privates', '.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()', 'getPostAdminControllerrejectService', true],
            'App\\Controller\\admin\\SettingadminController:index' => ['privates', '.service_locator.4XYvBdG.App\\Controller\\admin\\SettingadminController::index()', 'getSettingadminControllerindexService', true],
            'App\\Controller\\admin\\SettingadminController:edit' => ['privates', '.service_locator.j3kKXma.App\\Controller\\admin\\SettingadminController::edit()', 'getSettingadminControllereditService', true],
            'App\\Controller\\admin\\SettingadminController:lists' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\admin\\SettingadminController::lists()', 'getSettingadminControllerlistsService', true],
            'App\\Controller\\admin\\UseradminController:index' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\admin\\UseradminController::index()', 'getUseradminControllerindexService', true],
            'App\\Controller\\admin\\UseradminController:new' => ['privates', '.service_locator.4XYvBdG.App\\Controller\\admin\\UseradminController::new()', 'getUseradminControllernewService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ActualiteController::index' => '?',
            'App\\Controller\\ActualiteController::show' => '?',
            'App\\Controller\\ActualiteController::category' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\admin\\PostAdminController::index' => '?',
            'App\\Controller\\admin\\PostAdminController::new' => '?',
            'App\\Controller\\admin\\PostAdminController::approve' => '?',
            'App\\Controller\\admin\\PostAdminController::reject' => '?',
            'App\\Controller\\admin\\SettingadminController::index' => '?',
            'App\\Controller\\admin\\SettingadminController::edit' => '?',
            'App\\Controller\\admin\\SettingadminController::lists' => '?',
            'App\\Controller\\admin\\UseradminController::index' => '?',
            'App\\Controller\\admin\\UseradminController::new' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ActualiteController:index' => '?',
            'App\\Controller\\ActualiteController:show' => '?',
            'App\\Controller\\ActualiteController:category' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\admin\\PostAdminController:index' => '?',
            'App\\Controller\\admin\\PostAdminController:new' => '?',
            'App\\Controller\\admin\\PostAdminController:approve' => '?',
            'App\\Controller\\admin\\PostAdminController:reject' => '?',
            'App\\Controller\\admin\\SettingadminController:index' => '?',
            'App\\Controller\\admin\\SettingadminController:edit' => '?',
            'App\\Controller\\admin\\SettingadminController:lists' => '?',
            'App\\Controller\\admin\\UseradminController:index' => '?',
            'App\\Controller\\admin\\UseradminController:new' => '?',
        ]);

        if (isset($container->privates['.service_locator.Uj7onLO'])) {
            return $container->privates['.service_locator.Uj7onLO'];
        }

        return $container->privates['.service_locator.Uj7onLO'] = $instance;
    }
}
