<?php

namespace ContainerCCh7kcj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSampanaControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y6oGcsp.App\Controller\admin\SampanaController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sampanaRepository' => ['privates', 'App\\Repository\\SampanaRepository', 'getSampanaRepositoryService', true],
        ], [
            'entityManager' => '?',
            'sampanaRepository' => 'App\\Repository\\SampanaRepository',
        ]))->withContext('App\\Controller\\admin\\SampanaController::new()', $container);

        if (isset($container->privates['.service_locator.y6oGcsp.App\\Controller\\admin\\SampanaController::new()'])) {
            return $container->privates['.service_locator.y6oGcsp.App\\Controller\\admin\\SampanaController::new()'];
        }

        return $container->privates['.service_locator.y6oGcsp.App\\Controller\\admin\\SampanaController::new()'] = $instance;
    }
}
