<?php

namespace ContainerCCh7kcj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUseradminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c6de2iA.App\Controller\admin\UseradminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c6de2iA.App\\Controller\\admin\\UseradminController::index()'] = ($container->privates['.service_locator.c6de2iA'] ?? $container->load('get_ServiceLocator_C6de2iAService'))->withContext('App\\Controller\\admin\\UseradminController::index()', $container);
    }
}
