<?php

namespace ContainerYbk5bLJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K8m4mRx.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'appAuthenticator' => ['privates', 'App\\Security\\AppAuthenticator', 'getAppAuthenticatorService', true],
        ], [
            'userPasswordHasher' => '?',
            'userAuthenticator' => '?',
            'entityManager' => '?',
            'appAuthenticator' => 'App\\Security\\AppAuthenticator',
        ]))->withContext('App\\Controller\\RegistrationController::register()', $container);

        if (isset($container->privates['.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()'])) {
            return $container->privates['.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()'];
        }

        return $container->privates['.service_locator.K8m4mRx.App\\Controller\\RegistrationController::register()'] = $instance;
    }
}
