<?php

namespace ContainerWgsCyAH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingadminControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c6de2iA.App\Controller\admin\SettingadminController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\admin\\SettingadminController::list()', $container);

        if (isset($container->privates['.service_locator.c6de2iA.App\\Controller\\admin\\SettingadminController::list()'])) {
            return $container->privates['.service_locator.c6de2iA.App\\Controller\\admin\\SettingadminController::list()'];
        }

        return $container->privates['.service_locator.c6de2iA.App\\Controller\\admin\\SettingadminController::list()'] = $instance;
    }
}
