<?php

namespace ContainerWgsCyAH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingadminControllerviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0A7H.F.App\Controller\admin\SettingadminController::view()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'em' => '?',
        ]))->withContext('App\\Controller\\admin\\SettingadminController::view()', $container);

        if (isset($container->privates['.service_locator.z0A7H.F.App\\Controller\\admin\\SettingadminController::view()'])) {
            return $container->privates['.service_locator.z0A7H.F.App\\Controller\\admin\\SettingadminController::view()'];
        }

        return $container->privates['.service_locator.z0A7H.F.App\\Controller\\admin\\SettingadminController::view()'] = $instance;
    }
}
