<?php

namespace ContainerX7bxp7F;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSampanaControllerviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._betyeT.App\Controller\admin\SampanaController::view()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._betyeT.App\\Controller\\admin\\SampanaController::view()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sampana' => ['privates', '.errored..service_locator._betyeT.App\\Entity\\Sampana', NULL, 'Cannot autowire service ".service_locator._betyeT": it needs an instance of "App\\Entity\\Sampana" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'sampana' => 'App\\Entity\\Sampana',
        ]))->withContext('App\\Controller\\admin\\SampanaController::view()', $container);
    }
}
