<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uf7tg7RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uf7tg7R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fivondronanna' => ['privates', '.errored..service_locator.uf7tg7R.App\\Entity\\Fivondronana', NULL, 'Cannot autowire service ".service_locator.uf7tg7R": it needs an instance of "App\\Entity\\Fivondronana" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'fivondronanna' => 'App\\Entity\\Fivondronana',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.uf7tg7R'])) {
            return $container->privates['.service_locator.uf7tg7R'];
        }

        return $container->privates['.service_locator.uf7tg7R'] = $instance;
    }
}
