<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GhopRuhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GhopRuh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mpiandrakitra' => ['privates', '.errored..service_locator.GhopRuh.App\\Entity\\Mpiandrakitra', NULL, 'Cannot autowire service ".service_locator.GhopRuh": it needs an instance of "App\\Entity\\Mpiandrakitra" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'mpiandrakitra' => 'App\\Entity\\Mpiandrakitra',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.GhopRuh'])) {
            return $container->privates['.service_locator.GhopRuh'];
        }

        return $container->privates['.service_locator.GhopRuh'] = $instance;
    }
}
