<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFivondronannaControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.umxKVur.App\Controller\admin\FivondronannaController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fivondronanaRepository' => ['privates', 'App\\Repository\\FivondronanaRepository', 'getFivondronanaRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'fivondronanaRepository' => 'App\\Repository\\FivondronanaRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\admin\\FivondronannaController::index()', $container);

        if (isset($container->privates['.service_locator.umxKVur.App\\Controller\\admin\\FivondronannaController::index()'])) {
            return $container->privates['.service_locator.umxKVur.App\\Controller\\admin\\FivondronannaController::index()'];
        }

        return $container->privates['.service_locator.umxKVur.App\\Controller\\admin\\FivondronannaController::index()'] = $instance;
    }
}
