<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFivondronannaControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uf7tg7R.App\Controller\admin\FivondronannaController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.uf7tg7R'] ?? $container->load('get_ServiceLocator_Uf7tg7RService'));

        if (isset($container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'])) {
            return $container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\admin\\FivondronannaController::edit()', $container);

        if (isset($container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'])) {
            return $container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'];
        }

        return $container->privates['.service_locator.uf7tg7R.App\\Controller\\admin\\FivondronannaController::edit()'] = $instance;
    }
}
