<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMpiandrakitraControllerviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RP3w4br.App\Controller\admin\MpiandrakitraController::view()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RP3w4br.App\\Controller\\admin\\MpiandrakitraController::view()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mpiandrakitra' => ['privates', '.errored..service_locator.RP3w4br.App\\Entity\\Mpiandrakitra', NULL, 'Cannot autowire service ".service_locator.RP3w4br": it needs an instance of "App\\Entity\\Mpiandrakitra" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'mpiandrakitra' => 'App\\Entity\\Mpiandrakitra',
        ]))->withContext('App\\Controller\\admin\\MpiandrakitraController::view()', $container);
    }
}
