<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMpiandrakitraControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GhopRuh.App\Controller\admin\MpiandrakitraController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.GhopRuh'] ?? $container->load('get_ServiceLocator_GhopRuhService'));

        if (isset($container->privates['.service_locator.GhopRuh.App\\Controller\\admin\\MpiandrakitraController::edit()'])) {
            return $container->privates['.service_locator.GhopRuh.App\\Controller\\admin\\MpiandrakitraController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\admin\\MpiandrakitraController::edit()', $container);

        if (isset($container->privates['.service_locator.GhopRuh.App\\Controller\\admin\\MpiandrakitraController::edit()'])) {
            return $container->privates['.service_locator.GhopRuh.App\\Controller\\admin\\MpiandrakitraController::edit()'];
        }

        return $container->privates['.service_locator.GhopRuh.App\\Controller\\admin\\MpiandrakitraController::edit()'] = $instance;
    }
}
