<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMpiandrakitraControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pipiuQ7.App\Controller\admin\MpiandrakitraController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mpiandritraRepository' => ['privates', 'App\\Repository\\MpiandrakitraRepository', 'getMpiandrakitraRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'mpiandritraRepository' => 'App\\Repository\\MpiandrakitraRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\admin\\MpiandrakitraController::index()', $container);

        if (isset($container->privates['.service_locator.pipiuQ7.App\\Controller\\admin\\MpiandrakitraController::index()'])) {
            return $container->privates['.service_locator.pipiuQ7.App\\Controller\\admin\\MpiandrakitraController::index()'];
        }

        return $container->privates['.service_locator.pipiuQ7.App\\Controller\\admin\\MpiandrakitraController::index()'] = $instance;
    }
}
