<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMpiandrakitra2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RP3w4br.App\Entity\Mpiandrakitra' shared service.
     *
     * @return \App\Entity\Mpiandrakitra
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RP3w4br": it needs an instance of "App\\Entity\\Mpiandrakitra" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
