<?php

namespace ContainerOMaYvBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingadminControllergeneratePdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYAceIU.App\Controller\admin\SettingadminController::generatePdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYAceIU.App\\Controller\\admin\\SettingadminController::generatePdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.kYAceIU.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.kYAceIU": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'user' => 'App\\Entity\\User',
        ]))->withContext('App\\Controller\\admin\\SettingadminController::generatePdf()', $container);
    }
}
