<?php

namespace ContainerNIl1KrC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteControllercategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3yATBZT.App\Controller\ActualiteController::category()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3yATBZT.App\\Controller\\ActualiteController::category()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.3yATBZT.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.3yATBZT": it needs an instance of "App\\Entity\\Category" but this type has been excluded because it\'s a Doctrine entity.'],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'category' => 'App\\Entity\\Category',
            'postRepository' => 'App\\Repository\\PostRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]))->withContext('App\\Controller\\ActualiteController::category()', $container);
    }
}
