<?php

namespace ContainerTxYANxz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostAdminControllerrejectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EhRzrPc.App\Controller\admin\PostAdminController::reject()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.EhRzrPc'] ?? $container->load('get_ServiceLocator_EhRzrPcService'));

        if (isset($container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()'])) {
            return $container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()'];
        }

        $instance = $a->withContext('App\\Controller\\admin\\PostAdminController::reject()', $container);

        if (isset($container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()'])) {
            return $container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()'];
        }

        return $container->privates['.service_locator.EhRzrPc.App\\Controller\\admin\\PostAdminController::reject()'] = $instance;
    }
}
