<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHUAsnZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHUAsnZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHUAsnZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHUAsnZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHUAsnZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'HUAsnZx',
    'container.build_id' => '07aab472',
    'container.build_time' => 1773747896,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHUAsnZx');
