<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAF3wVm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAF3wVm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAF3wVm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAF3wVm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAF3wVm\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAF3wVm',
    'container.build_id' => '14095a9b',
    'container.build_time' => 1770905757,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAF3wVm');
