<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNIl1KrC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNIl1KrC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNIl1KrC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNIl1KrC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNIl1KrC\App_KernelDevDebugContainer([
    'container.build_hash' => 'NIl1KrC',
    'container.build_id' => '03e63db8',
    'container.build_time' => 1771241186,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNIl1KrC');
